### ISSUE TITLE
Missing V1Patch document

### ISSUE THREAD

**Issue by tripledes** [kubevirt/client-python#16]
While looking for information about patching objects, I've noticed `V1Patch.md` seems to be missing from the `docs` directory.

The document is linked on the [DefaultApi.md](https://github.com/kubevirt/client-python/blob/master/docs/DefaultApi.md).

**Comment by lukas-bednar** [comment]
It seems to come from `k8s.io/apimachinery/pkg/apis/meta/v1/types.go`, definition of Patch object is not part of openapi.json definition, so that is probably reason why it is not included in client.

But I can not find it in [kubernetes-client/python](https://github.com/kubernetes-client/python) neither ...

**Comment by tripledes** [comment]
@lukas-bednar thanks, that makes sense. Thing is, it get a bit confusing as it's mentioned also on the docstring for `patch_*` methods, for instance [here](https://github.com/kubevirt/client-python/blob/master/kubevirt/apis/default_api.py#L3243), so not sure what would be the best to either include it in the docs or remove its mentions ... Anyway, I'll have a look to the kubevirt/k8s code to see if and how it applies.

**Comment by pkliczewski** [comment]
Not needed anymore.
