### ISSUE TITLE
No auth headers

### ISSUE THREAD

**Issue by ClaudiuLSH** [kubevirt/client-python#28]
Hi,

I'm trying to use the API but with a service account and not kubeconfig:
```
from os import environ
import kubevirt


with open('/run/secrets/kubernetes.io/serviceaccount/token', 'r') as file:
    token = file.read()

kubevirt.configuration.api_key['authorization'] = token
kubevirt.configuration.api_key_prefix['authorization'] = 'Bearer'
kubevirt.configuration.ssl_ca_cert = '/run/secrets/kubernetes.io/serviceaccount/ca.crt'
kubevirt.configuration.host = f'https://{environ["KUBERNETES_SERVICE_HOST"]}'
kubevirt.configuration.debug = True
kubevirt_api = kubevirt.DefaultApi()

kubevirt_api.check_health()
```
It failed with:
```
send: b'GET /apis/subresources.kubevirt.io/v1alpha3/healthz HTTP/1.1\r\nHost: 10.43.0.1\r\nAccept-Encoding: identity\r\nAccept: application/json\r\nContent-Type: application/json\r\nUser-Agent: Swagger-Codegen/v0.29.0-78-g5de00f25/python\r\n\r\n'
reply: 'HTTP/1.1 401 Unauthorized\r\n'
```
I manually inserted auth token in rest.py at line 129: `headers['Authorization'] = f'Bearer {token}'`
Now the API calls are working fine:
```
send: b'GET /apis/subresources.kubevirt.io/v1alpha3/healthz HTTP/1.1\r\nHost: 10.43.0.1\r\nAccept-Encoding: identity\r\nAccept: application/json\r\nContent-Type: application/json\r\nUser-Agent: Swagger-Codegen/v0.29.0-78-g5de00f25/python\r\nAuthorization: Bearer TOKEN\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
2020-05-26 12:55:40,797 DEBUG https://10.43.0.1:443 "GET /apis/subresources.kubevirt.io/v1alpha3/healthz HTTP/1.1" 200 334
2020-05-26 12:55:40,797 DEBUG response body: {
 "apiserver": {
  "connectivity": "ok",
  "version": {
   "buildDate": "2020-04-16T11:35:47Z",
   "compiler": "gc",
   "gitCommit": "e0fccafd69541e3750d460ba0f9743b90336f24f",
   "gitTreeState": "clean",
   "gitVersion": "v1.17.5",
   "goVersion": "go1.13.9",
   "major": "1",
   "minor": "17",
   "platform": "linux/amd64"
  }
 }
}
```

Is this how the configuration auth details should be set?

**Comment by cccs-kevin** [comment]
/remove-lifecycle stale

I used the `kubeconfig` file and I can confirm that no token/API key is passed to the [ApiClient](https://github.com/kubevirt/client-python/blob/8f953cbc6c1bbbc20de9c0f86cb1222737a159f0/kubevirt/apis/default_api.py#L40) upon initialization which prevents all API calls from been authenticated correctly. 

Rather than the fix proposed above by @ClaudiuLSH (I don't think the variable `token` is accessible in the `request` method in `rest.py` as of writing this), I suggest replacing this `else` statement's contents [here](https://github.com/kubevirt/client-python/blob/8f953cbc6c1bbbc20de9c0f86cb1222737a159f0/kubevirt/apis/default_api.py#L38) with the following:
```            
if not config.api_client:
    auth_header = None
    auth_token = None
    if config.api_key.get("authorization"):
        auth_header = "authorization"
        auth_token = config.api_key["authorization"]
    config.api_client = ApiClient(header_name=auth_header, header_value=auth_token)
self.api_client = config.api_client
```
This way the authorization token will be passed to the ApiClient correctly and will be used for all API calls made by the ApiClient.

PS. I understand that this code is auto-generated, but I'm not sure how to fix it at the root.
